### ISSUE TITLE
Patch YAML by id fails to find

### ISSUE THREAD

**Issue by josephburnett** [josephburnett/jd#25]
a.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 8080
```
patch:
```
@ ["spec","template","spec","containers",{"name":"nginx"},"ports",0]
- 8080
+ 8081
```
error:
```
Invalid diff. Expected object with id {"name":"nginx"} but found none
```
Expected clean apply.
