### ISSUE TITLE
YAML key "on" interpreted as a bool value when translating from YAML

### ISSUE THREAD

**Issue by kelbyers** [josephburnett/jd#97]
While trying to make use of the `-t=yaml2json` functionality, I keep getting an error:

```
❯ jd -t=yaml2json android.yml
2025/05/27 14:31:40 unsupported key type bool
```

My test file that I am trying to convert just happens to be a GitHub workflow file, which contains the key `on`.

```yaml
name: Android CI

on:
  push:
    branches: [XXXmain]
  pull_request:
    branches: [XXXmain]
```

If I use the `yq` tool to convert the file to JSON, it understands that `on:` is a string when used as a key:
```json
{
  "on": {
    "push": {
      "branches": [
        "XXXmain"
      ]
    }
}
```
